version: '3.8'

services:
  catalog.api:
    container_name: catalog.api
    build:
      context: .
      dockerfile: Catalog/Catalog.API/Dockerfile
    environment:
       - ASPNETCORE_ENVIRONMENT=Development
       - ASPNETCORE_URLS=http://+:5000
    depends_on:
       - authorization.api
    ports:
      - 5000:5000

  orders.api:
    container_name: orders.api
    build:
      context: .
      dockerfile: Orders/Orders.API/Dockerfile
    environment:
       - ASPNETCORE_ENVIRONMENT=Development
       - ASPNETCORE_URLS=http://+:5001
    depends_on:
       - authorization.api
    ports:
      - 5001:5001
      
  authorization.api:
    container_name: authorization.api
    build:
      context: .
      dockerfile: Auth/Authorization.API/Dockerfile
    environment:
       - ASPNETCORE_ENVIRONMENT=Development
       - ASPNETCORE_URLS=http://+:5002
    ports:
      - 5002:5002
  
  comments.api:
    container_name: comments.api
    build:
      context: .
      dockerfile: Comments/Comments.API/Dockerfile
    environment:
       - ASPNETCORE_ENVIRONMENT=Development
       - ASPNETCORE_URLS=http://+:5003
    depends_on:
       - authorization.api
    ports:
      - 5003:5003

  nginx:
    image: nginx
    container_name: nginx
    ports:
       - 80:80
    volumes:
       - ./Proxy/gateway/nginx/conf.d:/etc/nginx/conf.d
       
networks:
  default:
    driver: bridge
    internal: false
    attachable: true
    ipam:
      driver: default
      config:
        - subnet: 192.168.0.0/24
          gateway: 192.168.0.1