version: '3.8'

services:
  catalog.api:
    container_name: catalog.api
    build:
      context: .
      dockerfile: Catalog/Catalog.API/Dockerfile
    environment:
       - ASPNETCORE_ENVIRONMENT=Development
       - ASPNETCORE_URLS=http://+:5000
    depends_on:
       - postgres
    ports:
      - 5000:5000
  
  pgadmin4:
    image: dpage/pgadmin4
    container_name: pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@gmail.com
      PGADMIN_DEFAULT_PASSWORD: admin
    depends_on:
      - postgres
    ports:
      - 8001:80    

  postgres:
    image: postgres:13.3
    container_name: postgres
    environment:
      POSTGRES_PASSWORD: postgres
    ports:
      - 5433:5432
  
  nginx:
    image: nginx
    container_name: nginx
    ports:
       - 80:80
    volumes:
       - ./Proxy/gateway/nginx/conf.d:/etc/nginx/conf.d
       
networks:
  default:
    driver: bridge
    internal: false
    attachable: true
    ipam:
      driver: default
      config:
        - subnet: 192.168.0.0/24
          gateway: 192.168.0.1